spring.cloud.gateway.server.webflux.routes[0].id=my-inventory
spring.cloud.gateway.server.webflux.routes[0].uri=lb://INVENTORY
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/inventory/**


spring.cloud.gateway.server.webflux.routes[1].id=my-order
spring.cloud.gateway.server.webflux.routes[1].uri=lb://orderservice
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/placeorder/**

name=udayapigateway
